# Generated by Django 4.0.1 on 2022-01-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveBigIntegerField(default=22),
            preserve_default=False,
        ),
    ]
