# Generated by Django 4.0.1 on 2022-01-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0002_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
